"""empty message

Revision ID: 993818011807
Revises: 0ad46a8c9274
Create Date: 2019-05-01 22:54:07.299038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993818011807'
down_revision = '0ad46a8c9274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behaviour')
    # ### end Alembic commands ###
